<div align="left">
    <h1> <font color="#cb1027"> Extração, Transformação e Carregamento dos Dados </h1>

<div align="center">
    <img src="https://www.fisica.ufmg.br/wp-content/uploads/2017/09/logo_df_fisica_ufmg.jpg"></img>
</div>

</div>

**Autor: João Victor Campos**


<font color="#cb1027" size=5> Fonte: </font>  [Física UFMG = Corpo Discente do 2º semestre de 2025]("https://www.fisica.ufmg.br/posgraduacao/corpo-discente/")
---

In [1]:
import pandas as pd
import locale
locale.setlocale(locale.LC_TIME, 'pt_BR.UTF-8')

'pt_BR.UTF-8'

In [2]:
# Link para extrair as tabelas das tags htlm
source_data: str = "https://www.fisica.ufmg.br/posgraduacao/corpo-discente/"

# Carregando os dados
mest, doc = pd.read_html(source_data, header=1)
mest["Modalidade"] = "Mestrado"
doc["Modalidade"] = "Doutorado" 

# Linha "morta" da tabela
mest = mest.head(-1) 

pos_grad = pd.concat([mest, doc], axis=0, ignore_index=True)     # DataFrame único com as duas tabelas
pos_grad = pos_grad.drop(columns="Matrícula") # Removendo coluna desnecessária 

pos_grad.sample(5)

,Aluno/a,Entrada,Área de Concentração,Orientador/a,Bolsista,Agência,Início bolsa,Término bolsa,Prazo término curso,Modalidade
138,Pedro Henrique Ferreira De Britto Braz,ago/22,Astrofísica,Wagner Corradi,Sim,FAPEMIG,set/22,ago/26,ago/27,Doutorado
105,Jane Elisa Rocha Guimarães,ago/22,Física,Ado Jorio,Sim,CNPQ,set/22,ago/26,ago/27,Doutorado
143,Thiago Seniuk Carrara,abr/25,Física,Ariete Righi,Sim,CAPES,mai/25,abr/29,abr/30,Doutorado
20,Gustavo Henrique Cassemiro de Souza,mar/25,Física,Walber Hugo de Brito,Sim,FAPEMIG,mar/25,fev/27,ago/27,Mestrado
103,Isadora Costa Coppo,out/25,Física,Não possui orientador cadastrado,Não,NaN,NaN,NaN,set/30,Doutorado

## <font color="#5e5e5e">Tratamento dos Dados</font>

__Renomeando Colunas__

In [3]:
print("Colunas Iniciais do Dataset:\n")
pos_grad.head(0)

Colunas Iniciais do Dataset:

Empty DataFrame
Columns: [Aluno/a, Entrada, Área de Concentração, Orientador/a, Bolsista, Agência, Início bolsa, Término bolsa, Prazo término curso, Modalidade]
Index: []

In [4]:
# Renomeando colunas 
pos_grad.columns = pos_grad.columns.str.replace(" ", "_").str.lower()
print(pos_grad.columns.tolist())

# Removendo caracteres ( ´ , ç , ^)
cols_rename: dict[str, str] = {
    "aluno/a": "aluno",
    "entrada": "inicio_curso",
    "área_de_concentração": "area",
    "orientador/a": "orientador",
    "agência": "agencia",
    "início_bolsa": "inicio_bolsa",
    "término_bolsa": "termino_bolsa",
    "prazo_término_curso": "termino_curso",
}
pos_grad = pos_grad.rename(columns=cols_rename)
print("Colunas renomeadas:\n")
pos_grad.head(0)

['aluno/a', 'entrada', 'área_de_concentração', 'orientador/a', 'bolsista', 'agência', 'início_bolsa', 'término_bolsa', 'prazo_término_curso', 'modalidade']
Colunas renomeadas:

Empty DataFrame
Columns: [aluno, inicio_curso, area, orientador, bolsista, agencia, inicio_bolsa, termino_bolsa, termino_curso, modalidade]
Index: []

In [5]:
# Reordenamento das colunas
ordem_cols = ["aluno", "modalidade", "area", "orientador", "inicio_curso", "termino_curso","bolsista","agencia", "inicio_bolsa", "termino_bolsa", ]
pos_grad = pos_grad[ordem_cols]
pos_grad

,aluno,modalidade,area,orientador,inicio_curso,termino_curso,bolsista,agencia,inicio_bolsa,termino_bolsa
0,Allan Gabriel Marques Lima,Mestrado,Física,Mario Mazzoni,abr/22,set/25,Não,NaN,NaN,NaN
1,Ana Carolina dos Santos,Mestrado,Física,Rogério Paniago,ago/23,jan/26,Não,NaN,NaN,NaN
2,André Felipe Alves Alencar,Mestrado,Física,Mario Mazzoni,ago/23,jan/26,Não,NaN,NaN,NaN
3,Barbara Alves Land Ferreira,Mestrado,Física,Simone Silva Alexandre,mar/23,mar/26,Não,NaN,NaN,NaN
4,Barbara Regina Melo Ribeiro,Mestrado,Física,Ana Maria de Paula (Daniela Ferreira – C),mar/24,ago/26,Sim,CAPES,mar/24,fev/26
...,...,...,...,...,...,...,...,...,...,...
147,Vinicius Aguiar Cardoso Godinho Baliza,Doutorado,Física,Não possui orientador cadastrado,ago/25,jul/30,Não,NaN,NaN,NaN
148,Vitor Assunção Moreira Lima,Doutorado,Física,Walber Hugo de Brito,jun/22,mai/27,Sim,FAPEMIG,jul/22,jun/26
149,Vitor Monteiro Macaroun,Doutorado,Física,Não possui orientador cadastrado,ago/25,jul/30,Não,NaN,NaN,NaN
150,Vitor Monteiro Pereira,Doutorado,Física,Raphael Drumond,mai/21,nov/26,Não,NaN,NaN,NaN
151,Welesson Henrique Natanal Silva,Doutorado,Física,Mario Mazzoni,abr/22,mar/27,Sim,FAPEMIG,abr/22,mar/26

__Tipos de dados__

In [6]:
pos_grad.dtypes

aluno            object
modalidade       object
area             object
orientador       object
inicio_curso     object
termino_curso    object
bolsista         object
agencia          object
inicio_bolsa     object
termino_bolsa    object
dtype: object

**Datas**

In [7]:
# Formatação de datas: mês/ano (jan/XX)
cols_datetime = ["inicio_curso", "inicio_bolsa", "termino_bolsa", "termino_curso"] 

for col in cols_datetime:
    pos_grad[col] = pd.to_datetime(pos_grad[col], format="%b/%y")
pos_grad.dtypes

aluno                    object
modalidade               object
area                     object
orientador               object
inicio_curso     datetime64[ns]
termino_curso    datetime64[ns]
bolsista                 object
agencia                  object
inicio_bolsa     datetime64[ns]
termino_bolsa    datetime64[ns]
dtype: object

**Booleanos**

In [8]:
# Convertendo bolsista para booleano
print(f"Valores únicos de bolsista (antes)\n{pos_grad["bolsista"].unique()}")

map_bolsista = {"sim": True, "não": False}
pos_grad["bolsista"] = pos_grad["bolsista"].str.lower().map(map_bolsista)

print(f"Valores únicos de bolsista (depois)\n{pos_grad["bolsista"].unique()}")
pos_grad.dtypes

Valores únicos de bolsista (antes)
['Não' 'Sim' 'SIm']
Valores únicos de bolsista (depois)
[False  True]

aluno                    object
modalidade               object
area                     object
orientador               object
inicio_curso     datetime64[ns]
termino_curso    datetime64[ns]
bolsista                   bool
agencia                  object
inicio_bolsa     datetime64[ns]
termino_bolsa    datetime64[ns]
dtype: object

__Tratamento de Strings__

In [9]:
print(f"Agências de Fomento (antes): {pos_grad["agencia"].unique()}")

# Correção do typo CNPq/PRPG e padronização em maiúscula
pos_grad["agencia"] = pos_grad["agencia"].str.upper()

print(f"Agências de Fomento (depois): {pos_grad["agencia"].unique()}")

Agências de Fomento (antes): [nan 'CAPES' 'CNPq/PRPG' 'FAPEMIG' 'CNPQ' 'CAPES/PRPG' 'CNPQ/PRPG']
Agências de Fomento (depois): [nan 'CAPES' 'CNPQ/PRPG' 'FAPEMIG' 'CNPQ' 'CAPES/PRPG']

In [10]:
# Formatando nome de pessoas com "Nome Sobrenome Sobrenome2" 
for col in ["aluno", "orientador"]:
    pos_grad[col] = pos_grad[col].str.title().str.strip()

In [11]:
pos_grad

,aluno,modalidade,area,orientador,inicio_curso,termino_curso,bolsista,agencia,inicio_bolsa,termino_bolsa
0,Allan Gabriel Marques Lima,Mestrado,Física,Mario Mazzoni,2022-04-01,2025-09-01,False,NaN,NaT,NaT
1,Ana Carolina Dos Santos,Mestrado,Física,Rogério Paniago,2023-08-01,2026-01-01,False,NaN,NaT,NaT
2,André Felipe Alves Alencar,Mestrado,Física,Mario Mazzoni,2023-08-01,2026-01-01,False,NaN,NaT,NaT
3,Barbara Alves Land Ferreira,Mestrado,Física,Simone Silva Alexandre,2023-03-01,2026-03-01,False,NaN,NaT,NaT
4,Barbara Regina Melo Ribeiro,Mestrado,Física,Ana Maria De Paula (Daniela Ferreira – C),2024-03-01,2026-08-01,True,CAPES,2024-03-01,2026-02-01
...,...,...,...,...,...,...,...,...,...,...
147,Vinicius Aguiar Cardoso Godinho Baliza,Doutorado,Física,Não Possui Orientador Cadastrado,2025-08-01,2030-07-01,False,NaN,NaT,NaT
148,Vitor Assunção Moreira Lima,Doutorado,Física,Walber Hugo De Brito,2022-06-01,2027-05-01,True,FAPEMIG,2022-07-01,2026-06-01
149,Vitor Monteiro Macaroun,Doutorado,Física,Não Possui Orientador Cadastrado,2025-08-01,2030-07-01,False,NaN,NaT,NaT
150,Vitor Monteiro Pereira,Doutorado,Física,Raphael Drumond,2021-05-01,2026-11-01,False,NaN,NaT,NaT
151,Welesson Henrique Natanal Silva,Doutorado,Física,Mario Mazzoni,2022-04-01,2027-03-01,True,FAPEMIG,2022-04-01,2026-03-01

**Tratamento de dados nulos**

In [12]:
pos_grad.isnull().sum()

aluno             0
modalidade        0
area              1
orientador        0
inicio_curso      0
termino_curso     0
bolsista          0
agencia          44
inicio_bolsa     45
termino_bolsa    45
dtype: int64

In [13]:
pos_grad.loc[pos_grad.area.isnull()]

,aluno,modalidade,area,orientador,inicio_curso,termino_curso,bolsista,agencia,inicio_bolsa,termino_bolsa
17,Francisco Gaspar Moreira Arvelos,Mestrado,NaN,Klaus Krambrock (Henrique F. V. Victória – C),2025-08-01,2028-02-01,True,CAPES,2025-08-01,2027-09-01

Um aluno está **sem área definida**. Como é apenas um registro *preencherei com a área mais frequente*.

> 💡 Em verdade, eu tenho conhecimento interno de que essa categorização é correta!

In [14]:
pos_grad.area.mode()

0    Física
Name: area, dtype: object

In [15]:
# Atribuindo área mais frequente ao dado faltante
pos_grad.loc[17, "area"] = "Física"
print(f"Alteração no aluno sem área => Física\n\n{pos_grad.loc[17]}")

Alteração no aluno sem área => Física

aluno                         Francisco Gaspar Moreira Arvelos
modalidade                                            Mestrado
area                                                    Física
orientador       Klaus Krambrock (Henrique F. V. Victória – C)
inicio_curso                               2025-08-01 00:00:00
termino_curso                              2028-02-01 00:00:00
bolsista                                                  True
agencia                                                  CAPES
inicio_bolsa                               2025-08-01 00:00:00
termino_bolsa                              2027-09-01 00:00:00
Name: 17, dtype: object

In [16]:
pos_grad.isnull().sum()

aluno             0
modalidade        0
area              0
orientador        0
inicio_curso      0
termino_curso     0
bolsista          0
agencia          44
inicio_bolsa     45
termino_bolsa    45
dtype: int64

Agora bastar verificar se os dados nulos em agência correspondem exclusivamente aqueles alunos sem bolsas.

In [17]:
# Sanity check
print(f"{'Teste de sanidade':-^100}")
num_bolsistas = pos_grad.bolsista.sum()
sem_bolsa = pos_grad.isnull().sum()['agencia']
print(f"{num_bolsistas + sem_bolsa = }")
print(f"Número total de alunos: {pos_grad.shape[0]}")
print("-"*100)

-----------------------------------------Teste de sanidade------------------------------------------
num_bolsistas + sem_bolsa = 152
Número total de alunos: 152
----------------------------------------------------------------------------------------------------

**Padronização da Coluna de Orientadores**

Algumas colunas possuem informação, além do orientador, também da co-orientação do aluno. Manterei **somente o orientador.**

In [18]:
pos_grad.orientador.unique()

array(['Mario Mazzoni', 'Rogério Paniago', 'Simone Silva Alexandre',
       'Ana Maria De Paula (Daniela Ferreira – C)', 'Bonnie Romano Zaire',
       'Não Possui Orientador Cadastrado', 'Emmanuel Araújo Pereira',
       'Gláuber Dorsch',
       'Karla Balzuweit – (Luiz Antônio Crruz Souza – C)',
       'Gustavo Guerrero', 'Wagner Corradi', 'Ricardo Wagner Nunes',
       'Livia Siman', 'Rodrigo Gribel Lacerda',
       'Klaus Krambrock (Henrique F. V. Victória – C)',
       'Ana Maria De Paula', 'Simone Alexandre', 'Walber Hugo De Brito',
       'Guilherme Da Silva Lima', 'Leonardo Campos', 'Ariete Righi',
       'Sebastião De Pádua', 'Bruce Vega', 'Von Braun Nascimento',
       'Michele Hidemi Ueno Guimarães', 'Pablo Saldanha',
       'Luis Eugênio Outon', 'Hélio Chacham', 'João Francisco Coelho',
       'Maurício Pinheiro', 'Marcos Assunção Pimenta',
       'Livia Siman Gomes', 'Nelson Yokomiso',
       'Myriano Henriques De Oliveira', 'Raphael Drumond',
       'Angelo Malachias', 'Karla Balzuweit', 'Ado Jorio De Vasconcelos',
       'Leandro Malard', 'Leonardo Neves', 'Ronald Dickman',
       'Gláuber Dorsch (Bruce Vega – C)',
       'Silvia Helena Alencar (Bonnie Zaire – C)',
       'Raphael Drumond (Emmanuel Araújo – C)',
       'Bruce Vega (Alexis Aguirre – C)', 'Luiz Gustavo Cançado',
       'Gerald Weber', 'Lucas Mol', 'Mário Mazzoni', 'Ado Jorio',
       'Roberto Paniago', 'Rodrigo Gribel (Ariete Righi – C)',
       'Nelson Yokomizo', 'Lucas Wardil',
       'Ronald Dickman (Maxim Lavrentovich – C)', 'Reinaldo Viana',
       'Carlos Basílio', 'João Francisco Coelho (Francisco Maia – C)',
       'Lucas Lages Wardil', 'Ubirajara Agero',
       'Maria Carolina De Oliveira Aguiar (O)',
       'Angelo Malachias (Mario Mazzoni – C)', 'Lívia Siman',
       'Bernardo Neves', 'Silvia Helena',
       'Glauber Dorsch (Nelson Yokomizo -C)',
       'Carlos Basilio Pinheiro (O)',
       'Leonardo Campos (Leandro Malard – C)',
       'Ubirajara Agero (Livia Siman – C)',
       'Maria Carolina De Oliveira Aguiar', 'Wagner Nunes Rodrigues (O)',
       'Maria Carolina Aguiar', 'Rodrigo Gribel',
       'Ubirajara Agero Batista', 'Silvia Helena Alencar', 'Juan Perez'],
      dtype=object)

In [19]:
re_parentese = r"\s*\(.*?\)"
pos_grad.orientador= pos_grad.orientador.str.replace(re_parentese, repl="", regex=True).str.strip()
print(pos_grad.orientador.unique())

['Mario Mazzoni' 'Rogério Paniago' 'Simone Silva Alexandre'
 'Ana Maria De Paula' 'Bonnie Romano Zaire'
 'Não Possui Orientador Cadastrado' 'Emmanuel Araújo Pereira'
 'Gláuber Dorsch' 'Karla Balzuweit –' 'Gustavo Guerrero' 'Wagner Corradi'
 'Ricardo Wagner Nunes' 'Livia Siman' 'Rodrigo Gribel Lacerda'
 'Klaus Krambrock' 'Simone Alexandre' 'Walber Hugo De Brito'
 'Guilherme Da Silva Lima' 'Leonardo Campos' 'Ariete Righi'
 'Sebastião De Pádua' 'Bruce Vega' 'Von Braun Nascimento'
 'Michele Hidemi Ueno Guimarães' 'Pablo Saldanha' 'Luis Eugênio Outon'
 'Hélio Chacham' 'João Francisco Coelho' 'Maurício Pinheiro'
 'Marcos Assunção Pimenta' 'Livia Siman Gomes' 'Nelson Yokomiso'
 'Myriano Henriques De Oliveira' 'Raphael Drumond' 'Angelo Malachias'
 'Karla Balzuweit' 'Ado Jorio De Vasconcelos' 'Leandro Malard'
 'Leonardo Neves' 'Ronald Dickman' 'Silvia Helena Alencar'
 'Luiz Gustavo Cançado' 'Gerald Weber' 'Lucas Mol' 'Mário Mazzoni'
 'Ado Jorio' 'Roberto Paniago' 'Rodrigo Gribel' 'Nelson Yokomizo'
 'Lucas Wardil' 'Reinaldo Viana' 'Carlos Basílio' 'Lucas Lages Wardil'
 'Ubirajara Agero' 'Maria Carolina De Oliveira Aguiar' 'Lívia Siman'
 'Bernardo Neves' 'Silvia Helena' 'Glauber Dorsch'
 'Carlos Basilio Pinheiro' 'Wagner Nunes Rodrigues'
 'Maria Carolina Aguiar' 'Ubirajara Agero Batista' 'Juan Perez']

In [20]:
pos_grad.orientador.sort_values().unique()
# Ado Jorio, Carlos Basilio, Glauber Dorsch, Karla Balzuweit, Livia Siman (3), Maria Carolina

array(['Ado Jorio', 'Ado Jorio De Vasconcelos', 'Ana Maria De Paula',
       'Angelo Malachias', 'Ariete Righi', 'Bernardo Neves',
       'Bonnie Romano Zaire', 'Bruce Vega', 'Carlos Basilio Pinheiro',
       'Carlos Basílio', 'Emmanuel Araújo Pereira', 'Gerald Weber',
       'Glauber Dorsch', 'Gláuber Dorsch', 'Guilherme Da Silva Lima',
       'Gustavo Guerrero', 'Hélio Chacham', 'João Francisco Coelho',
       'Juan Perez', 'Karla Balzuweit', 'Karla Balzuweit –',
       'Klaus Krambrock', 'Leandro Malard', 'Leonardo Campos',
       'Leonardo Neves', 'Livia Siman', 'Livia Siman Gomes',
       'Lucas Lages Wardil', 'Lucas Mol', 'Lucas Wardil',
       'Luis Eugênio Outon', 'Luiz Gustavo Cançado', 'Lívia Siman',
       'Marcos Assunção Pimenta', 'Maria Carolina Aguiar',
       'Maria Carolina De Oliveira Aguiar', 'Mario Mazzoni',
       'Maurício Pinheiro', 'Michele Hidemi Ueno Guimarães',
       'Myriano Henriques De Oliveira', 'Mário Mazzoni',
       'Nelson Yokomiso', 'Nelson Yokomizo',
       'Não Possui Orientador Cadastrado', 'Pablo Saldanha',
       'Raphael Drumond', 'Reinaldo Viana', 'Ricardo Wagner Nunes',
       'Roberto Paniago', 'Rodrigo Gribel', 'Rodrigo Gribel Lacerda',
       'Rogério Paniago', 'Ronald Dickman', 'Sebastião De Pádua',
       'Silvia Helena', 'Silvia Helena Alencar', 'Simone Alexandre',
       'Simone Silva Alexandre', 'Ubirajara Agero',
       'Ubirajara Agero Batista', 'Von Braun Nascimento',
       'Wagner Corradi', 'Wagner Nunes Rodrigues', 'Walber Hugo De Brito'],
      dtype=object)

Como estratégia, vou deixar apenas nome e sobrenome dos orientadores.

In [21]:
def separa_nome_sobrenome(nome_completo: str) -> str:
    """Padronizar os nomes do DataFrame em nome e sobrenome"""
    nomes: list[str] = nome_completo.split()[:2]
    nome, sobrenome = nomes
    novo_nome =  nome + " " + sobrenome
    return novo_nome

In [22]:
pos_grad.orientador = pos_grad.orientador.apply(separa_nome_sobrenome)

In [23]:
pos_grad.orientador.sort_values().unique()

array(['Ado Jorio', 'Ana Maria', 'Angelo Malachias', 'Ariete Righi',
       'Bernardo Neves', 'Bonnie Romano', 'Bruce Vega', 'Carlos Basilio',
       'Carlos Basílio', 'Emmanuel Araújo', 'Gerald Weber',
       'Glauber Dorsch', 'Gláuber Dorsch', 'Guilherme Da',
       'Gustavo Guerrero', 'Hélio Chacham', 'João Francisco',
       'Juan Perez', 'Karla Balzuweit', 'Klaus Krambrock',
       'Leandro Malard', 'Leonardo Campos', 'Leonardo Neves',
       'Livia Siman', 'Lucas Lages', 'Lucas Mol', 'Lucas Wardil',
       'Luis Eugênio', 'Luiz Gustavo', 'Lívia Siman', 'Marcos Assunção',
       'Maria Carolina', 'Mario Mazzoni', 'Maurício Pinheiro',
       'Michele Hidemi', 'Myriano Henriques', 'Mário Mazzoni',
       'Nelson Yokomiso', 'Nelson Yokomizo', 'Não Possui',
       'Pablo Saldanha', 'Raphael Drumond', 'Reinaldo Viana',
       'Ricardo Wagner', 'Roberto Paniago', 'Rodrigo Gribel',
       'Rogério Paniago', 'Ronald Dickman', 'Sebastião De',
       'Silvia Helena', 'Simone Alexandre', 'Simone Silva',
       'Ubirajara Agero', 'Von Braun', 'Wagner Corradi', 'Wagner Nunes',
       'Walber Hugo'], dtype=object)

Remoção de acentuações, corrigirá alguns casos como *Livia Siman* e *Carlos Basílio*

In [24]:
pos_grad.orientador = pos_grad.orientador.str.replace("í","i").str.replace("á", "a")

In [25]:
pos_grad.orientador.sort_values().unique()

array(['Ado Jorio', 'Ana Maria', 'Angelo Malachias', 'Ariete Righi',
       'Bernardo Neves', 'Bonnie Romano', 'Bruce Vega', 'Carlos Basilio',
       'Emmanuel Araújo', 'Gerald Weber', 'Glauber Dorsch',
       'Guilherme Da', 'Gustavo Guerrero', 'Hélio Chacham',
       'João Francisco', 'Juan Perez', 'Karla Balzuweit',
       'Klaus Krambrock', 'Leandro Malard', 'Leonardo Campos',
       'Leonardo Neves', 'Livia Siman', 'Lucas Lages', 'Lucas Mol',
       'Lucas Wardil', 'Luis Eugênio', 'Luiz Gustavo', 'Marcos Assunção',
       'Maria Carolina', 'Mario Mazzoni', 'Mauricio Pinheiro',
       'Michele Hidemi', 'Myriano Henriques', 'Nelson Yokomiso',
       'Nelson Yokomizo', 'Não Possui', 'Pablo Saldanha',
       'Raphael Drumond', 'Reinaldo Viana', 'Ricardo Wagner',
       'Roberto Paniago', 'Rodrigo Gribel', 'Rogério Paniago',
       'Ronald Dickman', 'Sebastião De', 'Silvia Helena',
       'Simone Alexandre', 'Simone Silva', 'Ubirajara Agero', 'Von Braun',
       'Wagner Corradi', 'Wagner Nunes', 'Walber Hugo'], dtype=object)

Precisamos dar conta de:
- Nomes Compostos: *Guilherme Da* e *Sebastião De*
- Typos: Nelson Yokomizo $\times$ Nelson Yokomiso

In [26]:
mask_sebastiao = (pos_grad["orientador"] == "Sebastião De")
mask_guilherme = (pos_grad["orientador"] == "Guilherme Da")

pos_grad.loc[mask_sebastiao, "orientador"] = "Sebastião de Pádua"
pos_grad.loc[mask_guilherme, "orientador"] = "Guilherme Da Silva"

pos_grad.orientador = pos_grad.orientador.str.replace("Nelson Yokomiso", "Nelson Yokomizo")

In [27]:
pos_grad

,aluno,modalidade,area,orientador,inicio_curso,termino_curso,bolsista,agencia,inicio_bolsa,termino_bolsa
0,Allan Gabriel Marques Lima,Mestrado,Física,Mario Mazzoni,2022-04-01,2025-09-01,False,NaN,NaT,NaT
1,Ana Carolina Dos Santos,Mestrado,Física,Rogério Paniago,2023-08-01,2026-01-01,False,NaN,NaT,NaT
2,André Felipe Alves Alencar,Mestrado,Física,Mario Mazzoni,2023-08-01,2026-01-01,False,NaN,NaT,NaT
3,Barbara Alves Land Ferreira,Mestrado,Física,Simone Silva,2023-03-01,2026-03-01,False,NaN,NaT,NaT
4,Barbara Regina Melo Ribeiro,Mestrado,Física,Ana Maria,2024-03-01,2026-08-01,True,CAPES,2024-03-01,2026-02-01
...,...,...,...,...,...,...,...,...,...,...
147,Vinicius Aguiar Cardoso Godinho Baliza,Doutorado,Física,Não Possui,2025-08-01,2030-07-01,False,NaN,NaT,NaT
148,Vitor Assunção Moreira Lima,Doutorado,Física,Walber Hugo,2022-06-01,2027-05-01,True,FAPEMIG,2022-07-01,2026-06-01
149,Vitor Monteiro Macaroun,Doutorado,Física,Não Possui,2025-08-01,2030-07-01,False,NaN,NaT,NaT
150,Vitor Monteiro Pereira,Doutorado,Física,Raphael Drumond,2021-05-01,2026-11-01,False,NaN,NaT,NaT
151,Welesson Henrique Natanal Silva,Doutorado,Física,Mario Mazzoni,2022-04-01,2027-03-01,True,FAPEMIG,2022-04-01,2026-03-01

## Salvando os Dados

In [28]:
# Armazenando a versão "limpa"
pos_grad.to_csv(path_or_buf="fisica-ufmg.csv", index=False)

---